name: Deploy Static Website

on:
  push:
    branches:
      - main


# These permissions are required for the OIDC token exchange.
permissions:
  id-token: write # Required for requesting the OIDC token
  contents: read  # Required to check out the repository code


env:
  AWS_REGION: us-east-1
  S3_BUCKET_ROOT: personal-website-customresourcestack--s3bucketroot-euxeofbkc8tn
  CLOUDFRONT_DISTRIBUTION_ID: E1GH1B8SMFLGEK
  IAM_ROLE_ARN: arn:aws:iam::726464323678:role/personal_website_cicd


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies & Build Static Site
        run: |
          npm ci
          npm run build
        working-directory: personal-site

      - name: Remove .html extensions for clean URLs
        # Manually rename files locally to enable cleaner looking URLs when deployed using S3.
        run: |
          echo "Renaming .html files for clean URLs..."
          # Find all .html files (excluding index.html) and rename them by stripping the extension
          find out -type f -name "*.html" ! -name "index.html" -exec sh -c '
            original_path="$1"
            new_path="${original_path%.html}"
            echo "Renaming: $original_path -> $new_path"
            mv "$original_path" "$new_path"
          ' sh {} \;
        working-directory: personal-site

      - name: Configure AWS Credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActionsDeploymentSession

      - name: Upload Standard Assets to S3
        # This handles all JS, CSS, images, etc. which still have extensions.
        # The --delete flag removes any files in S3 that are no longer in the 'out/' directory
        run: |
          aws s3 sync out/ s3://${{ env.S3_BUCKET_ROOT }} --delete
        working-directory: personal-site

      - name: Set Content-Type for Clean URLs (HTML files)
        # This step targets the files we renamed and forces the correct MIME type.
        run: |
          echo "Setting Content-Type: text/html for clean URL objects..."
          find out -type f ! -name "*.*" -exec sh -c '
            FILE_PATH="$1"
            OBJECT_KEY="${FILE_PATH#out/}" # Get the key relative to the 'out/' directory
            echo "Uploading HTML object: $OBJECT_KEY"
            aws s3 cp "$FILE_PATH" s3://${{ env.S3_BUCKET_ROOT }}/$OBJECT_KEY \
              --content-type "text/html"
          ' sh {} \;
        working-directory: personal-site

      - name: Invalidate CloudFront Cache
        # The '/*' path ensures all assets are re-fetched by the CDN
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
